### PR TITLE
Fix #120

### LINKED ISSUE #120: Listbakcup in pretty mode fails
##### Issue details:

* Issue type: **Bug**
* Impact: **Low**
* How often it happens: **Always**
* Brief description of the issue: In listbackup workflow with pretty option enabled appears and extra line between each backup.
* Work-around, if any: this only happen when there are backups in the database without size and duration.

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 2.3.0

### PR DESCRIPTION
**Pull request by NefixEstrada**
##### PR details:

* PR type (**Bug Fixing** / **New Feature** / **Enhancement** / **Other?**): Bug Fixing
* Reference to related issue (issue link): #120 
* Impact (**Low** / **High** / **Critical** / **Urgent**): Low
* Did you test this PR? Yes
* Brief description of the changes in this PR: This issue appeared because there was no parameter passed to the functions. With this commit this also stops happening, since if the value is null, now returns a "-"

### CODE REVIEW

File: usr/share/drlm/lib/backup-functions.sh [hunk 1]
```diff
@@ -524,6 +526,8 @@ function check_backup_size_status() {
 }
 
 function check_backup_time_status() {
+  if [ -z $1 ]; then echo -n "%-15"; fi
```
Comment (proura) [inline usr/share/drlm/lib/backup-functions.sh]:
```
if [ -z $1 ]; then 
    local duration="-"
else 
    local duration="$1" 
fi
```

File: usr/share/drlm/lib/backup-functions.sh [hunk 2]
```diff
@@ -524,6 +526,8 @@ function check_backup_size_status() {
...
+
 	local duration="$1"
```
Comment (proura) [inline usr/share/drlm/lib/backup-functions.sh]: delete this line

File: usr/share/drlm/lib/backup-functions.sh [hunk 3]
```diff
@@ -503,8 +503,10 @@ function get_client_used_mb ()
 }
 
 function check_backup_size_status() {
+  if [ -z $1 ]; then echo -n "%-15"; fi
```
Comment (proura) [inline usr/share/drlm/lib/backup-functions.sh]:
```
if [ -z $1 ]; then
    local input_size="-"
else
    local input_size="$1"
fi
```
and before line 519 do 
```
if [ "$input_size == "-" ]; then 
    echo -n "%-15s";
elif ...
```

File: usr/share/drlm/lib/backup-functions.sh [hunk 4]
```diff
@@ -503,8 +503,10 @@ function get_client_used_mb ()
...
+
     local input_size="$1"
```
Comment (proura) [inline usr/share/drlm/lib/backup-functions.sh]: delete this line
